name: CI

on: [push, pull_request]

jobs:
  file-conventions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unzip a file
        run: unzip -n path-to-file.zip
