name: Build & test on ubuntu

on: [push, pull_request]

jobs:
  sanitycheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # needed because of commit-lint, see https://github.com/conventional-changelog/commitlint/issues/3376
          fetch-depth: 0
      - name: Install dependencies of commitlint
        run: sudo apt install --yes npm && npm install @commitlint/config-conventional
      - name: Run tests to validate our plugins
        run: yarn add --dev jest typescript ts-jest @types/jest && yarn jest
      - name: Validate current commit (last commit) with commitlint
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

